### ISSUE TITLE
Questions about BRCA-molecular benchmark dataset

### ISSUE THREAD

**Issue by jonghyunlee1993** [trislaz/gigassl#3]
Hello, I am a student currently conducting research on breast cancer subtypes, and I came across your recent publication on the topic. Your findings have left a deep impression on me, and I am interested in pursuing a follow-up study based on your research. However, I have some questions regarding the dataset used in your study.

In particular, I noticed that you used the BRCA-molecular dataset in your research, which was estimated as a binary classification problem. As molecular types are typically classified as Luminal A, Luminal B, HER2, and TNBC, I was wondering about the criteria that were employed to generate the two labels used in the binary classification. Additionally, could you kindly confirm the TCGA IDs and any other relevant information used to gather the data?

I apologize if there is any confusion on my part, and I appreciate your assistance in clarifying these matters. 

Thank you for your time.

**Comment by trislaz** [comment]
Hello Jonghyun, 

Thank you for your interest !

Indeed, because of their supposed phenotypic relationship, we thought it appropriate to bring together the two luminal classes A and B under a single class.
Finally, because of their small number in the dataset (95) we decided  to remove the HER2+ from it, to easily perform the "tiny dataset" experiment. The molecular profiling task therefore is a binary classification task, classes being TNBC and Luminal cancers.

You can find all the TCGA IDs and labels in the subdir `tables` (https://github.com/trislaz/gigassl/blob/main/tables/tnbc.csv) and the used splits to perform the experiments in the `splitdirs` subdir (https://github.com/trislaz/gigassl/tree/main/splitdirs/tnbc)

Regards
